"""Session-bundle manifest contract.

`SessionManifest` is the shape of ``manifest.yaml`` inside
``~/halcytone/sessions/{session_id}/`` (see README §"Session bundle"). It is
the cross-language handoff point: halcytone-publish writes it, AgentGrounds
reads it. The JSON Schema mirror lives at ``manifest.schema.json`` next to
this module and is regenerated by ``scripts/regen_manifest_schema.py``.

`ended_at` is the completion marker per the README: ``None`` means the
session is still in progress; a populated datetime means AgentGrounds may
pick up the bundle.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict

from halcytone_contracts.session import SessionId


class SessionManifest(BaseModel):
    """Metadata for a completed-or-in-progress session bundle on disk."""

    model_config = ConfigDict(extra="forbid")

    session_id: SessionId
    started_at: datetime
    ended_at: datetime | None = None
    duration_s: int
    sensors: list[str]
    baselines: dict[str, float]
    summary: dict[str, float]
    artifacts: dict[str, str]


__all__ = ["SessionManifest"]
